module.exports = {
    citizenDataView: [
        {
            label:'Nombre: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'nombres',
        },
        {
            label:'Apellido Paterno: ',
            type:'text',
            placeholder:'Garcia',
            required: true,
            name: 'apellido_paterno',
        },
        {
            label:'Apellido Materno: ',
            type:'text',
            placeholder:'Juarez',
            required: true,
            name: 'apellido_materno',
        },
        {
            label:'Calle: ',
            type:'text',
            placeholder:'Laguna de San Cristobal',
            required: true,
            name: 'calle',
        },
        {
            label:'Número Exterior: ',
            type:'text',
            placeholder:'42',
            required: true,
            name: 'numero_exterior',
        },
        {
            label:'Número Interior: ',
            type:'text',
            placeholder:'54',
            required: true,
            name: 'numero_interior',
        },
        {
            label:'C. P.: ',
            type:'text',
            placeholder:'11320',
            required: true,
            name: 'codigo_postal',
        },
        {
            label:'Alcadía: ',
            type:'text',
            placeholder:'Selecciona una opción',
            required: true,
            name: 'alcaldia',
            inputType:'select',
            items: [{value:'gam', label:'Álvaro Obregón'}, {value:'gol', label:'Azcapotzalco'},{value:'gam', label:'Benito Juárez'}, {value:'gol', label:'Coyoacan'},{value:'gam', label:'Cuajimalpa'}, {value:'gol', label:'Cuautémoc'},{value:'gam', label:'Gustavo A. Madero'}, {value:'gol', label:'Iztacalco'},{value:'gam', label:'Izrapalapa'}, {value:'gol', label:'Magdalena Contreras'},{value:'gam', label:'Miguel Hidalgo'}, {value:'gol', label:'Milpa Alta'},{value:'gam', label:'Tláhuac'}, {value:'gol', label:'Tlalpan'},{value:'gam', label:'Venueztiano Carranza'}, {value:'gol', label:'Xochimilco'}],
        },
        {
            label:'Teléfono: ',
            type:'text',
            placeholder:'0000000000',
            required: true,
            name: 'numero_telefono',
        },
        {
            label:'Correo electrónico: ',
            type:'text',
            placeholder:'correoele@domino.com',
            required: true,
            name: 'email',
        },
        {
            label:'Colonia: ',
            type:'text',
            placeholder:'Selecciona una opción: ',
            required: true,
            name: 'colonia',
        },
        {
            label:'Documento de identificación',
            type:'text',
            placeholder:'INE',
            required: true,
            name: 'documento_identificacion_oficial',
        },
    ],
    loginEMView: [{
        label:'Email: ',
        type:'email',
        placeholder:'correoele@domino.com',
        required: true,
        name: 'email',
    },
    {
        label:'Contraseña: ',
        type:'password',
        placeholder:'',
        required: true,
        name: 'password',
    },],
    loginCIView: [{
        label:'Email: ',
        type:'email',
        placeholder:'correoele@domino.com',
        required: true,
        name: 'city',
    },
    {
        label:'Contraseña: ',
        type:'password',
        placeholder:'',
        required: true,
        name: 'password',
    },],
    treeDataView: [{
        label:'Sobre calle: ',
        type:'text',
        placeholder:'Mar mediterraneo',
        required: true,
        name: 'calle_arbol',
    },
    {
        label:'Y calle',
        type:'text',
        placeholder:'Mar rojo',
        required: true,
        name: 'calle_adyacente_1',
    },
    {
        label:'Y calle',
        type:'text',
        placeholder:'Mar rojo',
        required: true,
        name: 'calle_adyacente_2',
    },
    {
        label:'C. P.: ',
        type:'text',
        placeholder:'11320',
        required: true,
        name: 'cp',
    },
    {
        label:'Alcadía: ',
        type:'text',
        placeholder:'Selecciona una opción',
        required: true,
        name: 'alcaldia_arrbol',
        inputType:'select',
        items: [{value:'gam', label:'Álvaro Obregón'}, {value:'gol', label:'Azcapotzalco'},{value:'gam', label:'Benito Juárez'}, {value:'gol', label:'Coyoacan'},{value:'gam', label:'Cuajimalpa'}, {value:'gol', label:'Cuautémoc'},{value:'gam', label:'Gustavo A. Madero'}, {value:'gol', label:'Iztacalco'},{value:'gam', label:'Izrapalapa'}, {value:'gol', label:'Magdalena Contreras'},{value:'gam', label:'Miguel Hidalgo'}, {value:'gol', label:'Milpa Alta'},{value:'gam', label:'Tláhuac'}, {value:'gol', label:'Tlalpan'},{value:'gam', label:'Venueztiano Carranza'}, {value:'gol', label:'Xochimilco'}],
    },
    {
        label:'Referencias: ',
        type:'textArea',
        placeholder:'',
        required: true,
        name: 'referencias',
    },
    {
        label:'Motivo: ',
        type:'textArea',
        placeholder:'',
        required: true,
        name: 'motivos',
    },
    {
        label:'Fotografias del árbol',
        type:'',
        placeholder:'Fotografias',
        required: true,
        name: 'fotos',
    },
    {
        label:'Colonia: ',
        type:'text',
        placeholder:'Selecciona una opción: ',
        required: true,
        name: 'colonia_arbol',
    }, 
    {
        label:'Tipo: ',
        type:'text',
        placeholder:'Selecciona una opción',
        required: true,
        name: 'tipo',
        inputType:'select',
        items: [{value:'Vía pública', label:'Vía pública'}, {value:'Propiedad privada', label:'Propiedad privada'}],
    },],
    privatDataView: [
        {
            label:'Alcadía: ',
            type:'text',
            placeholder:'Selecciona una opción',
            required: true,
            name: 'alcaldia',
            inputType:'select',
            items: [{value:'Topiara', label:'Poda o derribo por ornamentación'}, {value:'Construcción', label:'Poda o derribo por construcción, remodelación o amplación'},{value:'Riesgo', label:'Derribo por riesgo '}],
        },
        {
            label:'Comprobante de propiedad',
            type:'',
            placeholder:'comprobante de propiedad',
            required: true,
            name: 'comprobante_propiedad',
        },
        {
            label:'Comprobante de domicilio',
            type:'',
            placeholder:'comprobante de domicilio',
            required: true,
            name: 'comprobante_domicilio',
        },
    ],
    constructionDataView: [
        {
            label:'Registro de Manifestación de Construcción de Tipo A, B o C o Licencia de Construcción Especial con sello de la Alcaldía.',
            type:'',
            placeholder:'Docuemento pdf',
            required: true,
            name: 'documento_registro',
        },
        {
            label:'Declaratoria ambiental',
            type:'',
            placeholder:'Documento pdf',
            required: true,
            name: 'documento_declaratoria',
        },
        {
            label:'Planos arquitectonicos',
            type:'',
            placeholder:'Documento pdf',
            required: true,
            name: 'documento_planos',
        },
    ],
    riesgoDataView: [
        {
            label:'Dictamen técnico',
            type:'',
            placeholder:'Docuemento pdf',
            required: true,
            name: 'documento_dictamen_riesgo',
        },
    ],
};