module.exports = {
    inputsFirstView: [
        {
            label:'Nombre: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'first_name',
        },
        {
            label:'Apellido Paterno: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'last_name_p',
        },
        {
            label:'Apellido Materno: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'last_name_m',
        },
        {
            label:'Calle: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'fe',
        },
        {
            label:'Número Exterior: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'fame',
        },
        {
            label:'Número Interior: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'fke',
        },
        {
            label:'C. P.: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'hjg',
        },
        {
            label:'Alcadía: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'hgjhg',
        },
        {
            label:'Teléfono: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'fvfdvfdge',
        },
        {
            label:'Correo electrónico: ',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'fifdgfdge',
        },
        {
            label:'Documento de identificación',
            type:'text',
            placeholder:'Mario',
            required: true,
            name: 'ffdgfdgme',
        },
    ],
    inputSecondView: [{
        label:'Nombre: ',
        type:'text',
        placeholder:'Mario',
        required: true,
        name: 'fifgdgme',
    },],
};